account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/<int:profile_id>', views.ProfileDetailView.as_view(), name='profile'),
    path('', views.dashboard, name='dashboard'),
]

dataset/urls.py
from django.urls import path
from . import views

app_name = 'dataset'

urlpatterns = [
    path('', views.DataSetIndexView.as_view(), name='index'),
    path('<int:pk>/', views.DataSetDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('new/', views.DataSetCreateView.as_view(), name='new'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

smartmobile_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('account.urls')),
                  path('model/', include('tf_model.urls', namespace='tf_model')),
                  path('dataset/', include('dataset.urls', namespace='dataset')),
                  path('project/', include('project.urls', namespace='project')),
                  path('api/', include('tf_model.api_urls')),
                  path('docs', include_docs_urls(title='API V.1')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dataset/models.py
from django.db import models
from django.contrib.auth.models import User


class DataSet(models.Model):
    TYPE_CHOICES = (
        ('text', 'text'),
        ('images', 'images'),
        ('audio', 'audio'),
    )
    name = models.CharField(max_length=250)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='data_set')
    created = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='text')

    def __str__(self):
        return self.name

dataset/forms.py
from django import forms
from .models import DataSet


class DataSetForm(forms.ModelForm):
    class Meta:
        model = DataSet
        exclude = ['id', 'user']

dataset/views.py
from .models import DataSet
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from .forms import DataSetForm


class DataSetIndexView(ListView):
    template_name = 'dataset/index.html'
    context_object_name = 'dataset_list'

    def get_queryset(self):
        return DataSet.objects.filter(user=self.request.user)


class DataSetDetailView(DetailView):
    model = DataSet
    template_name = 'dataset/detail.html'


class DataSetCreateView(CreateView):
    model = DataSet
    template_name = 'dataset/new.html'
    form_class = DataSetForm
    form_valid_message = 'DataSet created successfully!'
    success_url = reverse_lazy('dataset:index')

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.save()
        return redirect('dataset:index')


def edit(request, pk, template_name='dataset/edit.html'):
    dataset = get_object_or_404(DataSet, pk=pk)
    form = DataSetForm(request.POST or None, instance=dataset)
    if form.is_valid():
        form.save()
        return redirect('dataset:index')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='dataset/confirm_delete.html'):
    dataset = get_object_or_404(DataSet, pk=pk)
    if request.method == 'POST':
        dataset.delete()
        return redirect('dataset:index')
    return render(request, template_name, {'object': dataset})

templates/dataset/confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-xs-2 col-sm-2"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Delete confirmation</div>
                        <div class="ibox-tools">
                            <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <div class="card" style="width:80%;">
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="alert alert-warning">
                                            Are you sure you want to delete {{ object }}?
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-danger">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dataset/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <h3 class="round3" style="text-align:center;">Dataset details:</h3>
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="card-title"> #{{ object.id }}</h5>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-3">Name</dt>
                    <dd class="col-sm-9">{{ oblect.name }}</dd>
                    <dt class="col-sm-3">Description</dt>
                    <dd class="col-sm-9">{{ object.description }}</dd>
                    <dt class="col-sm-3">Created</dt>
                    <dd class="col-sm-9">{{ object.created }}</dd>
                    <dt class="col-sm-3">Type</dt>
                    <dd class="col-sm-9">{{ object.type }}</dd>
                </dl>
            </div>
        </div>
        <br>
        {% if object.tfmodel %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title"> Related model:
                        <a href="{% url 'tf_model:detail' object.tfmodel.pk %}">
                            <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                    data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                        </a></h5>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.name }}</dd>
                        <dt class="col-sm-3">Description</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.details }}</dd>
                        <dt class="col-sm-3">Created</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.created }}</dd>
                        <dt class="col-sm-3">Type</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.type }}</dd>
                    </dl>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/dataset/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
        <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">Edit Dataset</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-2 col-form-label">
                                {{ field.errors }}
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10">
                                {% render_field field class="form-control" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>

{#    <div class="container-fluid">#}
{#        <div class="row">#}
{#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
{#            <div class="col-md-10 col-xs-10 col-sm-10 ">#}
{#                <br/>#}
{#                <h6 style="text-align:center;"><font color="red"> All fields are required</font></h6>#}
{#            </div>#}
{#            <div class="col-md-1 col-xs-1 col-sm-1">#}
{#            </div>#}
{#        </div>#}
{#        <div class="row">#}
{#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
{#            <div class="col-md-10 col-xs-10 col-sm-10">#}
{#                <form method="post" novalidate>#}
{#                    {% csrf_token %}#}
{#                    {% for hidden_field in form.hidden_fields %}#}
{#                        {{ hidden_field }}#}
{#                    {% endfor %}#}
{#                    {% for field in form.visible_fields %}#}
{#                        <div class="form-group">#}
{#                            {{ field.label_tag }}#}
{#                            {% render_field field class="form-control" %}#}
{#                            {% if field.help_text %}#}
{#                                <small class="form-text text-muted">{{ field.help_text }}</small>#}
{#                            {% endif %}#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                    <button type="submit" class="btn btn-primary">submit</button>#}
{#                </form>#}
{#                <br>#}
{#            </div>#}
{#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
{#        </div>#}
{#    </div>#}
{% endblock %}

templates/dataset/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="ibox">
            <div class="ibox-head">
                {#                    <div class="ibox-title">#}
                <div class="w-75">
                    <span class="ibox-title">Datasets</span>
                </div>
                <div class="w-25 text-right">
                    <a href="{% url 'dataset:new' %}">
                        <button type="button" class="btn btn-success">
                            Add
                        </button>
                    </a>
                </div>
                {#                    </div>#}
            </div>
            <div class="ibox-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Created</th>
                            <th>Type</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for dataset in dataset_list %}
                            <tr>
                                <td>
                                    {{ dataset.name }}
                                </td>
                                <td>
                                    {{ dataset.created }}

                                </td>
                                <td>
                                    {{ dataset.type }}
                                </td>
                                <td>
                                    <a href="{% url 'dataset:detail' dataset.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                                    </a>
                                    <a href="{% url 'dataset:edit' dataset.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Edit"><i class="fa fa-pencil font-14"></i></button>
                                    </a>
                                    <a href="{% url 'dataset:delete' dataset.pk %}">
                                        <button class="btn btn-default btn-xs" data-toggle="tooltip"
                                                data-original-title="Delete"><i class="fa fa-trash font-14"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dataset/new.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">New Dataset</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-2 col-form-label">
                                {{ field.errors }}
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10">
                                {% render_field field class="form-control" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>



{% endblock %}