account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/<int:profile_id>', views.ProfileDetailView.as_view(), name='profile'),
    path('', views.dashboard, name='dashboard'),
]

smartmobile_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('account.urls')),
                  path('model/', include('tf_model.urls', namespace='tf_model')),
                  path('dataset/', include('dataset.urls', namespace='dataset')),
                  path('project/', include('project.urls', namespace='project')),
                  path('api/', include('tf_model.api_urls')),
                  path('docs', include_docs_urls(title='API V.1')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tf_model/urls.py
from django.urls import path
from . import views

app_name = 'tf_model'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.TFModelDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('new/', views.TFModelCreateView.as_view(), name='new'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('model/<int:model_id>/version/new', views.VersionCreateView.as_view(), name='new_version'),
    path('version/<int:version_id>/file/new', views.ModelFileView.as_view(), name='new_file'),
    path('model/<int:model_id>/version/new', views.VersionCreateView.as_view(), name='new_version'),
]

tf_model/models.py
import uuid as uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from dataset.models import DataSet


class TFModel(models.Model):
    TYPE_CHOICES = (
        ('img_cl', 'Image Classification'),
        ('custom', 'Custom'),
    )
    name = models.CharField(max_length=250)
    details = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='tf_models')
    dataset = models.OneToOneField(DataSet, null=True, blank=True, on_delete=models.SET_NULL)

    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='custom')

    def __str__(self):
        return self.name


class ModelVersion(models.Model):
    name = models.CharField(max_length=250, blank=False)
    tf_model = models.ForeignKey(TFModel, on_delete=models.CASCADE,
                                 related_name='model_versions')
    unique_together = ('tf_model', 'name')

    def __str__(self):
        return self.name


class ModelFile(models.Model):
    FORMAT_CHOICES = (
        ('tflite', 'tensorflow lite model'),
        ('pb', 'Custom'),
        ('h5', 'keras model'),
    )
    name = models.CharField(max_length=255, blank=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    version = models.ForeignKey(ModelVersion, on_delete=models.CASCADE,
                                related_name='model_files')
    converted = models.BooleanField(default=False, editable=False)
    optimized = models.BooleanField(default=False, editable=False)
    format = models.CharField(max_length=10, choices=FORMAT_CHOICES, default='tflite')
    file = models.FileField()

    # path = models.FilePathField()

    def __str__(self):
        return self.name

tf_model/forms.py
from django import forms
from django.db.models import Q

from .models import TFModel, ModelVersion, ModelFile
from dataset.models import DataSet


class VersionForm(forms.ModelForm):
    class Meta:
        model = ModelVersion
        exclude = ('tf_model',)


class FileForm(forms.ModelForm):
    class Meta:
        model = ModelFile
        exclude = ('version',)


class TFModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TFModelForm, self).__init__(*args, **kwargs)
        user = self.initial.get('user', None) or self.instance.user
        if self.instance.dataset:
            dataset_id = self.instance.dataset.pk
            self.fields['dataset'].queryset = DataSet.objects.filter(user=user.id).exclude(
                id__in=TFModel.objects.filter(Q(user=user.id) & ~Q(dataset_id__exact=dataset_id)).exclude(
                    dataset__isnull=True).values_list('dataset_id')
            )
        else:
            self.fields['dataset'].queryset = DataSet.objects.filter(user=user.id).exclude(
                id__in=TFModel.objects.filter(user=user.id).exclude(dataset__isnull=True).values_list('dataset_id')
            )
        # self.fields['dataset'].queryset = TFModel.objects.filter(user=user.id)

    class Meta:
        model = TFModel
        exclude = ('user',)

tf_model/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import TFModelForm, VersionForm, FileForm
from .models import TFModel, ModelVersion, ModelFile
from django.views.generic import ListView, DetailView, CreateView


class IndexView(ListView):
    template_name = 'tf_model/index.html'
    context_object_name = 'tf_model_list'

    def get_queryset(self):
        return TFModel.objects.filter(user=self.request.user)


class VersionCreateView(CreateView):
    model = ModelVersion
    template_name = 'tf_model/new_version.html'
    form_class = VersionForm
    form_valid_message = 'Version created successfully!'

    def form_valid(self, form):
        form = form.save(commit=False)
        form.tf_model = get_object_or_404(TFModel, pk=self.kwargs['model_id'])
        form.save()
        return redirect('tf_model:detail', pk=self.kwargs['model_id'])


class TFModelDetailView(DetailView):
    model = TFModel
    template_name = 'tf_model/detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(TFModelDetailView, self).get_context_data(**kwargs)
    #     context['versions'] = self.object.model_versions.all()
    #     return context


class TFModelCreateView(CreateView):
    model = TFModel
    template_name = 'tf_model/new.html'
    form_class = TFModelForm
    form_valid_message = 'TF Model created successfully!'

    def get_initial(self):
        initial = super(TFModelCreateView, self).get_initial()
        initial.update({'user': self.request.user})
        return initial

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.save()
        return redirect('tf_model:index')


class ModelFileView(CreateView):
    model = ModelFile
    template_name = 'tf_model/new_file.html'
    form_class = FileForm
    form_valid_message = 'Model file uploaded successfully!'

    def form_valid(self, form):
        form = form.save(commit=False)
        model_version = get_object_or_404(ModelVersion, pk=self.kwargs['version_id'])
        form.version = model_version
        form.save()
        return redirect('tf_model:detail', model_version.tf_model.id)


@login_required()
def edit(request, pk, template_name='tf_model/edit.html'):
    tf_model = get_object_or_404(TFModel, pk=pk)
    form = TFModelForm(request.POST or None, instance=tf_model)
    if form.is_valid():
        form.save()
        return redirect('tf_model:index')
    return render(request, template_name, {'form': form})


@login_required()
def delete(request, pk, template_name='tf_model/confirm_delete.html'):
    tf_model = get_object_or_404(TFModel, pk=pk)
    if request.method == 'POST':
        tf_model.delete()
        return redirect('tf_model:index')
    return render(request, template_name, {'object': tf_model})

templates/tf_model/confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-xs-2 col-sm-2"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Delete confirmation</div>
                        <div class="ibox-tools">
                            <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <div class="card" style="width:80%;">
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="alert alert-warning">
                                            Are you sure you want to delete {{ object }}?
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-danger">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/tf_model/delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row"></div>
        <br/>
        <div class="row">
            <div class="col-md-2 col-xs-2 col-sm-2"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="alert alert-warning">
                            Are you sure you want to delete {{ object }}?
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">
                        Delete
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/tf_model/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <h3 class="round3" style="text-align:center;">TF Model details:</h3>
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="card-title"> #{{ object.id }}</h5>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-3">Name</dt>
                    <dd class="col-sm-9">{{ object.name }}</dd>
                    <dt class="col-sm-3">Details</dt>
                    <dd class="col-sm-9">{{ object.details }}</dd>
                    <dt class="col-sm-3">Created</dt>
                    <dd class="col-sm-9">{{ object.created }}</dd>
                    <dt class="col-sm-3">UID</dt>
                    <dd class="col-sm-9">{{ object.uuid }}</dd>
                    <dt class="col-sm-3">Type</dt>
                    <dd class="col-sm-9">{{ object.type }}</dd>
                    <dt class="col-sm-3">Dataset</dt>
                    <dd class="col-sm-9">{{ object.dataset }}</dd>

                </dl>
            </div>
        </div>
        <br>
        {% if object.dataset %}
            <div class="ibox">
                <div class="ibox-head">
                    <div class="w-60">
                        <span class="ibox-title">Dataset: {{ object.dataset.name }} </span>
                    </div>
                    <div class="ibox-tools w-20">
                        <a href="{% url 'dataset:detail' object.dataset.pk %}">
                            <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                    data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                        </a></h5>
                        <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
                    </div>
                </div>
                <div class="ibox-body">
                    <dl class="row">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">{{ object.dataset.name }}</dd>
                        <dt class="col-sm-3">Description</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.description }}</dd>
                        <dt class="col-sm-3">Type</dt>
                        <dd class="col-sm-9">{{ object.tfmodel.type }}</dd>
                    </dl>

                </div>
            </div>
        {% endif %}

        <div class="ibox">
            <div class="ibox-head">
                <div class="w-60">
                    <span class="ibox-title">Versions:</span>
                </div>
                <div class="ibox-tools w-10">
                    <a href="{% url 'tf_model:new_version' object.id %}">
                        <button type="button" class="btn btn-success">
                            Add version
                        </button>
                    </a>
                    <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
                </div>
            </div>

            <div class="ibox-body">
                {% for version in object.model_versions.all %}
                    <div class="ibox">
                        <div class="ibox-head">
                            <div class="w-60">
                                <span class="ibox-title">#{{ version.name }} files: </span>
                            </div>
                            <div class="ibox-tools w-20">
                                <a href="{% url 'tf_model:new_file' version.id %}">
                                    <button type="button" class="btn btn-success">
                                        Upload new file
                                    </button>
                                </a>
                                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <div class="ibox-body">
                            {% for file in version.model_files.all %}
                                <div class="card">
                                    <div class="card-body">
                                        <dl class="row">
                                            <dt class="col-sm-3">Title:</dt>
                                            <dd class="col-sm-9">{{ file.name }}</dd>
                                            <dt class="col-sm-3">Name:</dt>
                                            <dd class="col-sm-9">
                                                <a href="{{ file.file.url }}">
                                                    {{ file.file.name }}
                                                </a> ({{ file.file.size|filesizeformat }})
                                            </dd>
                                            <dt class="col-sm-3">UID:</dt>
                                            <dd class="col-sm-9">{{ file.uuid }}</dd>
                                            <dt class="col-sm-3">Original format:</dt>
                                            <dd class="col-sm-9">{{ file.format }}</dd>
                                        </dl>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>


        {#        <div class="row">#}
        {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
        {#            <div class="col-md-8 col-xs-8 col-sm-8">#}
        {#                <h3 class="round3" style="text-align:center;">Versions:</h3>#}
        {#            </div>#}
        {#            <div class="col-md-2 col-xs-1 col-sm-1">#}
        {#                <a href="{% url 'tf_model:new_version' object.id %}">#}
        {#                    <button type="button" class="btn btn-success">#}
        {#                        New Version#}
        {#                    </button>#}
        {#                </a>#}
        {#            </div>#}
        {#        </div>#}
        {#        {% for version in object.model_versions.all %}#}
        {#            <div class="card">#}
        {#                <div class="card-header">#}
        {#                    <h5 class="card-title"> #{{ version.name }}</h5>#}
        {#                </div>#}
        {#                <div class="container">#}
        {#                    <div class="card-body">#}
        {#                        <dl class="row">#}
        {#                            <div class="card">#}
        {#                                <div class="card-header">#}
        {#                                    <div class="container-fluid">#}
        {#                                        <div class="row">#}
        {#                                            <div class="col">#}
        {#                                                <h4 class="round3" style="text-align:center;">Files:</h4>#}
        {#                                            </div>#}
        {#                                            <div class="col">#}
        {#                                                <a href="{% url 'tf_model:new_file' version.id %}">#}
        {#                                                    <button type="button" class="btn btn-success">#}
        {#                                                        Upload new file#}
        {#                                                    </button>#}
        {#                                                </a>#}
        {#                                            </div>#}
        {#                                        </div>#}
        {#                                    </div>#}
        {#                                </div>#}
        {#                                {% for file in version.model_files.all %}#}
        {#                                    <div class="container m-2">#}
        {#                                        {{ file.name }}#}
        {#                                    </div>#}
        {#                                    <div class="card m-2">#}
        {#                                        <div class="card-body">#}
        {#                                            <dl class="row">#}
        {#                                                <dt class="col-sm-3">Name:</dt>#}
        {#                                                <dd class="col-sm-9">#}
        {#                                                    <a href="{{ file.file.url }}">#}
        {#                                                        {{ file.file.name }}#}
        {#                                                    </a> ({{ file.file.size|filesizeformat }})#}
        {#                                                </dd>#}
        {#                                                <dt class="col-sm-3">UID:</dt>#}
        {#                                                <dd class="col-sm-9">{{ file.uuid }}</dd>#}
        {#                                                <dt class="col-sm-3">Original format:</dt>#}
        {#                                                <dd class="col-sm-9">{{ file.format }}</dd>#}
        {#                                            </dl>#}
        {#                                        </div>#}
        {#                                    </div>#}
        {#                                {% endfor %}#}
        {##}
        {#                            </div>#}
        {#                        </dl>#}
        {##}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        {% endfor %}#}
    </div>
{% endblock %}

templates/tf_model/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">Edit model</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <div class="col-sm-2 col-form-label">
                            {{ field.errors }}
                            {{ field.label_tag }}
                        </div>
                        <div class="col-sm-10">
                            {% render_field field class="form-control" %}
                        </div>
                        {% if field.help_text %}
                            <sfvmall class="form-text text-muted">{{ field.help_text }}</sfvmall>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>

    {#    <div class="container-fluid">#}
    {#        <div class="row">#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#            <div class="col-md-10 col-xs-10 col-sm-10 ">#}
    {#                <br/>#}
    {#                <h6 style="text-align:center;"><font color="red"> All fields are required</font></h6>#}
    {#            </div>#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1">#}
    {#            </div>#}
    {#        </div>#}
    {#        <div class="row">#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#            <div class="col-md-10 col-xs-10 col-sm-10">#}
    {#                <form method="post" novalidate>#}
    {#                    {% csrf_token %}#}
    {#                    {% for hidden_field in form.hidden_fields %}#}
    {#                        {{ hidden_field }}#}
    {#                    {% endfor %}#}
    {#                    {% for field in form.visible_fields %}#}
    {#                        <div class="form-group">#}
    {#                            {{ field.label_tag }}#}
    {#                            {% render_field field class="form-control" %}#}
    {#                            {% if field.help_text %}#}
    {#                                <small class="form-text text-muted">{{ field.help_text }}</small>#}
    {#                            {% endif %}#}
    {#                        </div>#}
    {#                    {% endfor %}#}
    {#                    <button type="submit" class="btn btn-primary">submit</button>#}
    {#                </form>#}
    {#                <br>#}
    {#            </div>#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

templates/tf_model/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="ibox">
            <div class="ibox-head">
                {#                    <div class="ibox-title">#}
                <div class="w-75">
                    <span class="ibox-title">Models</span>
                </div>
                <div class="w-25 text-right">
                    <a href="{% url 'tf_model:new' %}">
                        <button type="button" class="btn btn-success">
                            Add
                        </button>
                    </a>
                </div>
                {#                    </div>#}
            </div>
            <div class="ibox-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Created</th>
                            <th>Type</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for model in tf_model_list %}
                            <tr>
                                <td>
                                    {{ model.name }}
                                </td>
                                <td>
                                    {{ model.created }}

                                </td>
                                <td>
                                    {{ model.type }}
                                </td>
                                <td>
                                    <a href="{% url 'tf_model:detail' model.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                                    </a>
                                    <a href="{% url 'tf_model:edit' model.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Edit"><i class="fa fa-pencil font-14"></i></button>
                                    </a>
                                    <a href="{% url 'tf_model:delete' model.pk %}">
                                        <button class="btn btn-default btn-xs" data-toggle="tooltip"
                                                data-original-title="Delete"><i class="fa fa-trash font-14"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/tf_model/new.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">New model</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-2 col-form-label">
                                {{ field.errors }}
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10">
                                {% render_field field class="form-control" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>



{% endblock %}

templates/tf_model/new_version.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">New Version</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group row">
                        <div class="col-sm-2 col-form-label">
                            {{ field.label_tag }}
                        </div>
                        <div class="col-sm-10">
                            {% render_field field class="form-control" %}
                        </div>
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>
        </div>
    </div>



{% endblock %}