account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/<int:profile_id>', views.ProfileDetailView.as_view(), name='profile'),
    path('', views.dashboard, name='dashboard'),
]

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.ProjectIndexView.as_view(), name='index'),
    path('<int:pk>/', views.ProjectDetailView.as_view(), name='detail'),
    path('new/', views.ProjectCreateView.as_view(), name='new'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

smartmobile_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('account.urls')),
                  path('model/', include('tf_model.urls', namespace='tf_model')),
                  path('dataset/', include('dataset.urls', namespace='dataset')),
                  path('project/', include('project.urls', namespace='project')),
                  path('api/', include('tf_model.api_urls')),
                  path('docs', include_docs_urls(title='API V.1')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/models.py
from django.db import models
from django.contrib.auth.models import User
from tf_model.models import TFModel


class Project(models.Model):
    name = models.CharField(max_length=250)
    details = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='project')
    tf_models = models.ManyToManyField(TFModel, blank=True)

    def __str__(self):
        return self.name

project/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple

from .models import Project, TFModel


class ProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['tf_models'].widget = CheckboxSelectMultiple()
        user = self.initial.get('user', None) or self.instance.user
        self.fields['tf_models'].queryset = TFModel.objects.filter(user=user.id)

    class Meta:
        model = Project
        exclude = ['id', 'user']

project/views.py
from .models import Project
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from .forms import ProjectForm


class ProjectIndexView(ListView):
    template_name = 'project/index.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.filter(user=self.request.user)


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project/detail.html'


class ProjectCreateView(CreateView):
    model = Project
    template_name = 'project/new.html'
    form_class = ProjectForm
    form_valid_message = 'Project created successfully!'
    success_url = reverse_lazy('project:index')

    def get_initial(self):
        initial = super(ProjectCreateView, self).get_initial()
        initial.update({'user': self.request.user})
        return initial

    def form_valid(self, form):
        project = form.save(commit=False)
        project.user = self.request.user
        project.save()
        for tf_model in form.cleaned_data['tf_models']:
            project.tf_models.add(tf_model)
        return redirect('project:index')


def edit(request, pk, template_name='project/edit.html'):
    project = get_object_or_404(Project, pk=pk)
    form = ProjectForm(request.POST or None, instance=project)
    if form.is_valid():
        form.save()
        return redirect('project:index')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='project/confirm_delete.html'):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('project:index')
    return render(request, template_name, {'object': project})

templates/project/confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-xs-2 col-sm-2"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Delete confirmation</div>
                        <div class="ibox-tools">
                            <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <div class="card" style="width:80%;">
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="alert alert-warning">
                                            Are you sure you want to delete {{ object }}?
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-danger">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/project/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <h3 class="round3" style="text-align:center;">Project details:</h3>
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>

        <div class="ibox">
            <div class="card-header">
                <h5 class="card-title"> #{{ object.id }}</h5>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-3">Name</dt>
                    <dd class="col-sm-9">{{ object.name }}</dd>
                    <dt class="col-sm-3">Details</dt>
                    <dd class="col-sm-9">{{ object.details }}</dd>
                </dl>
            </div>
        </div>

        <div class="ibox">
            <div class="ibox-head">
                <div class="w-60">
                    <span class="ibox-title">Models:</span>
                </div>
                <div class="ibox-tools w-10">
                    <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
                </div>
            </div>
            <div class="ibox-body">
                {% for model in object.tf_models.all %}
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title"> {{ model.name }}
                                <a href="{% url 'tf_model:detail' model.pk %}">
                                    <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                            data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                                </a>
                            </h5>
                        </div>

                        <div class="card-body">
                            <dl class="row">
                                <dt class="col-sm-3">Details:</dt>
                                <dd class="col-sm-9">{{ model.details }}</dd>
                            </dl>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>


        <br>
    </div>
{% endblock %}

templates/project/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">Edit Project</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>
        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {% if field|field_type == 'modelmultiplechoicefield' %}
                        <div class="form-group row" >
                            <div class="col-sm-2 col-form-label">
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10 check-list">
                                {% render_field field class="checkbox-row" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-2 col-form-label">
                                {{ field.errors }}
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10">
                                {% render_field field class="form-control" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>

                    {% endif %}
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>

    {#    <div class="container-fluid">#}
    {#        <div class="row">#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#            <div class="col-md-10 col-xs-10 col-sm-10 ">#}
    {#                <br/>#}
    {#                <h6 style="text-align:center;"><font color="red"> All fields are required</font></h6>#}
    {#            </div>#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1">#}
    {#            </div>#}
    {#        </div>#}
    {#        <div class="row">#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#            <div class="col-md-10 col-xs-10 col-sm-10">#}
    {#                <form method="post" novalidate>#}
    {#                    {% csrf_token %}#}
    {#                    {% for hidden_field in form.hidden_fields %}#}
    {#                        {{ hidden_field }}#}
    {#                    {% endfor %}#}
    {#                    {% for field in form.visible_fields %}#}
    {#                        <div class="form-group">#}
    {#                            {{ field.label_tag }}#}
    {#                            {% render_field field class="form-control" %}#}
    {#                            {% if field.help_text %}#}
    {#                                <small class="form-text text-muted">{{ field.help_text }}</small>#}
    {#                            {% endif %}#}
    {#                        </div>#}
    {#                    {% endfor %}#}
    {#                    <button type="submit" class="btn btn-primary">submit</button>#}
    {#                </form>#}
    {#                <br>#}
    {#            </div>#}
    {#            <div class="col-md-1 col-xs-1 col-sm-1"></div>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

templates/project/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="ibox">
            <div class="ibox-head">
                {#                    <div class="ibox-title">#}
                <div class="w-75">
                    <span class="ibox-title">Projects</span>
                </div>
                <div class="w-25 text-right">
                    <a href="{% url 'project:new' %}">
                        <button type="button" class="btn btn-success">
                            Add
                        </button>
                    </a>
                </div>
                {#                    </div>#}
            </div>
            <div class="ibox-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Created</th>
                            <th>Type</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>
                                    {{ project.name }}
                                </td>
                                <td>
                                    {{ project.created }}

                                </td>
                                <td>
                                    {{ project.type }}
                                </td>
                                <td>
                                    <a href="{% url 'project:detail' project.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Show"><i class="fa fa-eye font-14"></i></button>
                                    </a>
                                    <a href="{% url 'project:edit' project.pk %}">
                                        <button class="btn btn-default btn-xs m-r-5" data-toggle="tooltip"
                                                data-original-title="Edit"><i class="fa fa-pencil font-14"></i></button>
                                    </a>
                                    <a href="{% url 'project:delete' project.pk %}">
                                        <button class="btn btn-default btn-xs" data-toggle="tooltip"
                                                data-original-title="Delete"><i class="fa fa-trash font-14"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/project/new.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">New Project</div>
            <div class="ibox-tools">
                <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
                <a class="fullscreen-link"><i class="fa fa-expand"></i></a>
            </div>
        </div>

        <div class="ibox-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {% if field|field_type == 'modelmultiplechoicefield' %}
                        <div class="form-group row">
                            <div class="col-sm-2 col-form-label">
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10 check-list">
                                {% render_field field class="checkbox-row" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="form-group row {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-2 col-form-label">
                                {{ field.errors }}
                                {{ field.label_tag }}
                            </div>
                            <div class="col-sm-10">
                                {% render_field field class="form-control" %}
                            </div>
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>

                    {% endif %}
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm-2 col-form-label">
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info">submit</button>
                    </div>
                </div>


        </div>
    </div>



{% endblock %}